steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudbuild-demo', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cloudbuild-demo']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'cloudbuild-demo', '--image', 'gcr.io/$PROJECT_ID/cloudbuild-demo', '--region', 'asia-southeast2', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/cloudbuild-demo'

options:
  logging: CLOUD_LOGGING_ONLY
